Repository flowcus-tracker/flowcus-fe, pull requests merged in 2025-03, with the labels that each got.

#4 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#5 Update README.md
  README.md
Labels: documentation

#7 updated readme
  README.md
Labels: documentation

#8 Set Timer and Circular Progress Indicator
  lib/pages/timer_page.dart
Labels: bug

#12 Ay 9 20250318 todo in timer
  .github/workflows/build.yml
  android/app/.cxx/Debug/471p1p11/arm64-v8a/.cmake/api/v1/reply/index-2025-03-21T01-20-08-0089.json
  android/app/.cxx/Debug/471p1p11/arm64-v8a/configure_fingerprint.bin
  android/app/.cxx/Debug/471p1p11/armeabi-v7a/.cmake/api/v1/reply/index-2025-03-21T01-20-10-0000.json
  android/app/.cxx/Debug/471p1p11/armeabi-v7a/configure_fingerprint.bin
  android/app/.cxx/Debug/471p1p11/x86/.cmake/api/v1/reply/index-2025-03-21T01-20-11-0820.json
  android/app/.cxx/Debug/471p1p11/x86/configure_fingerprint.bin
  android/app/.cxx/Debug/471p1p11/x86_64/.cmake/api/v1/reply/index-2025-03-21T01-20-13-0424.json
  android/app/.cxx/Debug/471p1p11/x86_64/configure_fingerprint.bin
  devtools_options.yaml
  lib/main.dart
  lib/pages/calendar_page.dart
  lib/pages/task_page.dart
  lib/pages/task_provider.dart
  lib/pages/timer_page.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#13 Added multiple timer options and updated UI
  lib/pages/task_provider.dart
  lib/pages/timer_page.dart
Labels: enhancement
